version: '3.7'


volumes:
  volume_db:
  volume_static:


networks:
  net_db:
  net_front:


services:
  redis:
    image: redis:5-alpine
    container_name: redis
    networks:
      - net_db
    ports:
      - "6379:6379"
    volumes:
      - volume_db:/data
    read_only: true
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s

  snakes:
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
    image: carrots/snakes-snakes:latest
    build: ./appcode/
    container_name: snakes
    user: root
    cap_add:
      - SYS_ADMIN
      - MKNOD
    security_opt:
      - apparmor:unconfined
    networks:
      - net_db
    command: snakes-run
    restart: always

  django:
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      SECRET_KEY: thisIsNotARealSecretKeyReally
    image: carrots/snakes-django:latest
    build: ./appcode/
    container_name: django
    networks:
      - net_db
      - net_front
    volumes:
      - volume_static:/srv/appenv/app/static
    command: django-run
    restart: always

  nginx:
    depends_on:
      - django
    image: carrots/snakes-nginx:latest
    build: ./nginx/
    container_name: nginx
    ports:
      - "8000:80"
    networks:
      - net_front
    volumes:
    volumes:
      - /var/cache/nginx
      - /var/run
      - volume_static:/srv/appenv/app/static
    restart: always

